name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'   # Only run when you push a tag like v1.1, v1.2

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write   # <-- needed for uploading to releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=ghosttrap.ico csr_generator_gui_full.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/csr_generator_gui_full.exe
