name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the build (optional)"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller csr_generator_gui_full.py --onefile --noconsole

    - name: Upload built EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: csr_generator_gui_full
        path: dist/csr_generator_gui_full.exe
