name: Build Windows EXE

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=ghosttrap.ico csr_generator_gui_full.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CSR_Generator_GUI
          path: dist/csr_generator_gui_full.exe
