name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller csr_generator_gui_full.py --onefile --noconsole --name csr_generator_gui_${{ github.ref_name }}

    - name: Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: dist/csr_generator_gui_${{ github.ref_name }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
